//
//  ContentView.swift
//  lect2
//
//  Created by Fanny on 2025/9/12.
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        ZStack{
            Color(red: 61/255, green: 145/255, blue: 64/255)
                .ignoresSafeArea()
            Rectangle()
                .trim(from: -0.5, to: 0.5)
                .frame(width: 110, height: 110)
                .rotationEffect(.degrees(340))
                .offset(x: 95, y: -90)
            Rectangle()
                .trim(from: -0.5, to: 0.5)
                .frame(width: 95, height: 60)
                .rotationEffect(.degrees(340))
                .foregroundStyle(Color(red: 210/225, green: 105/255, blue: 30/255))
                .offset(x: 95, y: -90)
            Rectangle()
                .trim(from: -0.5, to: 0.5)
                .frame(width: 110, height: 110)
                .rotationEffect(.degrees(290))
                .offset(x: -95, y: -90)
            Rectangle()
                .trim(from: -0.5, to: 0.5)
                .frame(width: 60, height: 95)
                .rotationEffect(.degrees(290))
                .foregroundStyle(Color(red: 210/225, green: 105/255, blue: 30/255))
                .offset(x: -95, y: -90)
            Ellipse()
                .frame(width: 370, height: 250)
                .foregroundStyle(Color(red: 227/255, green: 168/255, blue: 105/255))
            Ellipse()
                .frame(width: 340, height: 180)
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: -8, y: -24)
            Ellipse()
                .frame(width: 80, height: 150)
                .foregroundStyle(Color(red: 1, green: 160/255, blue: 0))
                .offset(x: 0, y: -110)
            Ellipse()
                .frame(width: 70, height: 130)
                .foregroundStyle(Color(red: 1, green: 1, blue: 0))
                .offset(x: -3, y: -120)
            Rectangle()
                .frame(width: 60, height: 7)
                .foregroundStyle(Color(red: 1, green: 160/255, blue: 0))
                .offset(x: 0, y: -157)
            Rectangle()
                .frame(width: 70, height: 7)
                .foregroundStyle(Color(red: 1, green: 160/255, blue: 0))
                .offset(x: 0, y: -130)
            Rectangle()
                .frame(width: 70, height: 7)
                .foregroundStyle(Color(red: 1, green: 160/255, blue: 0))
                .offset(x: 0, y: -103)
            Rectangle()
                .frame(width: 60, height: 7)
                .foregroundStyle(Color(red: 1, green: 160/255, blue: 0))
                .offset(x: 0, y: -78)
            Circle()
                .frame(width: 90, height: 90)
                .foregroundStyle(Color(red: 220/255, green: 220/255, blue: 220/255))
                .offset(x: -80, y: -20)
            Circle()
                .frame(width: 75, height: 75)
                .foregroundStyle(Color(red: 250/255, green: 240/255, blue: 230/255))
                .offset(x: -88, y: -26)
            Circle()
                .frame(width: 90, height: 90)
                .foregroundStyle(Color(red: 220/255, green: 220/255, blue: 220/255))
                .offset(x: 80, y: -20)
            Circle()
                .frame(width: 75, height: 75)
                .foregroundStyle(Color(red: 250/255, green: 240/255, blue: 230/255))
                .offset(x: 70, y: -26)
            Ellipse()
                .frame(width: 15, height: 70)
                .offset(x: 70, y: -18)
            Ellipse()
                .frame(width: 8, height: 50)
                .foregroundStyle(Color(red: 65/255, green: 105/255, blue: 1))
                .offset(x: 70, y: -10)
            Ellipse()
                .frame(width: 10, height: 25)
                .foregroundStyle(Color(red: 1, green: 1, blue: 1))
                .offset(x: 70, y: -33)
            Ellipse()
                .frame(width: 15, height: 70)
                .offset(x: -70, y: -18)
            Ellipse()
                .frame(width: 8, height: 50)
                .foregroundStyle(Color(red: 65/255, green: 105/255, blue: 1))
                .offset(x: -70, y: -10)
            Ellipse()
                .frame(width: 10, height: 25)
                .foregroundStyle(Color(red: 1, green: 1, blue: 1))
                .offset(x: -70, y: -33)
            Rectangle()
                .frame(width: 220, height: 7)
                .offset(x: 00, y: 50)
            Rectangle()
                .trim(from: -0.5, to: 0.5)
                .frame(width: 23, height: 23)
                .rotationEffect(.degrees(135))
                .foregroundStyle(Color(red: 1, green: 1, blue: 1))
                .offset(x: 88, y: 54)
            Rectangle()
                .trim(from: -0.5, to: 0.5)
                .frame(width: 23, height: 23)
                .rotationEffect(.degrees(135))
                .foregroundStyle(Color(red: 1, green: 1, blue: 1))
                .offset(x: -88, y: 54)
            
            Text("hi")
                .font(.system(size: 100))
                .foregroundStyle(.black)
                .offset(x: 0, y: -250)
            Ellipse()
                .frame(width: 13, height: 145)
                .rotationEffect(.degrees(12))
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: 50, y: -150)
            Ellipse()
                .frame(width: 13, height: 145)
                .rotationEffect(.degrees(348))
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: -50, y: -150)
            Ellipse()
                .frame(width: 13, height: 145)
                .rotationEffect(.degrees(300))
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: -190, y: -50)
            Ellipse()
                .frame(width: 13, height: 145)
                .rotationEffect(.degrees(260))
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: -190, y: 30)
            Ellipse()
                .frame(width: 13, height: 145)
                .rotationEffect(.degrees(60))
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: 190, y: -50)
            Ellipse()
                .frame(width: 13, height: 145)
                .rotationEffect(.degrees(100))
                .foregroundStyle(Color(red: 1, green: 210/255, blue: 132/255))
                .offset(x: 190, y: 30)
                
        }
    }
}

#Preview {
    ContentView()
}
